"""Underwriting schemas."""
from typing import Optional, Any
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict


class UnderwriteRequest(BaseModel):
    applicant_id: int = Field(..., ge=100000, le=999999, description="Home Credit applicant ID")
    model_id: Optional[str] = Field(None, description="Optional model to execute (e.g. xgboost, lightgbm, logistic, chained_ensemble, cascade_hurdle)")

    model_config = ConfigDict(json_schema_extra={"example": {"applicant_id": 370920, "model_id": "chained_ensemble"}})



class SHAPFactor(BaseModel):
    feature: str
    label: Optional[str] = None
    category: Optional[str] = None
    value: str
    shap: float
    effect: str
    description: str


class PolicyEvidence(BaseModel):
    source: str
    authority: str
    title: str
    page: Optional[str] = None
    version_date: Optional[str] = None
    jurisdiction: Optional[str] = None
    content: str


class ModelInformation(BaseModel):
    model_id: Optional[str] = "xgboost"
    model_type: str = "XGBoost"
    task: str = "Probability of Default (Binary Classification)"
    training_dataset: str = "Home Credit Default Risk"
    model_version: str
    feature_count: Optional[int] = None
    pipeline_details: Optional[dict] = None
    shap_note: str = (
        "SHAP values indicate feature contribution to model output. "
        "They should NOT be interpreted as causal explanations."
    )


class UnderwritingResult(BaseModel):
    request_id: str
    applicant_id: int
    timestamp: datetime
    probability_of_default: float = Field(..., ge=0.0, le=1.0)
    risk_tier: str
    decision: str
    policy_reason: str
    risk_increasing_factors: list[SHAPFactor]
    risk_reducing_factors: list[SHAPFactor]
    regulatory_evidence: list[PolicyEvidence]
    model_information: ModelInformation
    policy_version: str
    policy_thresholds: Optional[dict] = None
    agent_assessment: Optional[str] = None
    disclaimer: str = (
        "RESEARCH PROTOTYPE ONLY. This assessment is generated by an "
        "experimental AI system for academic research purposes. It does "
        "not constitute a credit decision by any financial institution. "
        "Not legally compliant. Not for production use."
    )


class UnderwritingListItem(BaseModel):
    request_id: str
    applicant_id: int
    timestamp: datetime
    probability_of_default: float
    risk_tier: str
    decision: str


class AgentChatRequest(BaseModel):
    applicant_id: int
    question: str
    underwriting_context: Optional[dict] = None


class AgentChatResponse(BaseModel):
    applicant_id: int
    question: str
    answer: str
    llm_available: bool
    disclaimer: str = (
        "This AI assistant uses the deterministic underwriting result as "
        "its source of truth. It does not invent financial information, "
        "regulatory requirements, or applicant details."
    )
